Loading config configs/Base-coco-stuff-10K-171.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.
Command Line Args: Namespace(config_file='configs/san_clip_vit_res4_coco.yaml', resume=False, eval_only=False, num_gpus=1, num_machines=1, machine_rank=0, dist_url='tcp://127.0.0.1:50155', opts=['SOLVER.IMS_PER_BATCH', '1', 'OUTPUT_DIR', 'output/', 'WANDB.NAME'])
Traceback (most recent call last):
  File "/data/zjy/sources/SAN/train_net.py", line 285, in <module>
    launch(
  File "/home/zjy/.conda/envs/san/lib/python3.9/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "/data/zjy/sources/SAN/train_net.py", line 262, in main
    cfg = setup(args)
  File "/data/zjy/sources/SAN/train_net.py", line 252, in setup
    cfg.merge_from_list(args.opts)
  File "/home/zjy/.conda/envs/san/lib/python3.9/site-packages/fvcore/common/config.py", line 143, in merge_from_list
    return super().merge_from_list(cfg_list)
  File "/home/zjy/.conda/envs/san/lib/python3.9/site-packages/yacs/config.py", line 223, in merge_from_list
    _assert_with_logging(
  File "/home/zjy/.conda/envs/san/lib/python3.9/site-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['SOLVER.IMS_PER_BATCH', '1', 'OUTPUT_DIR', 'output/', 'WANDB.NAME']; it must be a list of pairs
